### ISSUE TITLE
Change to use PSID format for port partitioning

### ISSUE THREAD

**Issue by andywingo** [Igalia/snabbswitch#101]
See http://tools.ietf.org/html/rfc7597

**Comment by dpino** [comment]
I have taken a look at the referred document. If my understanding is correct it goes like this:

It is necessary to define a *sharing ratio* (R) and a *maximum number of continue ports* (M). Given these constant values, a port value (16-bit) is divided following this bit pattern:

0                          8                         15
+---------------+----------+------+-------------------+
|                     P                               |
----------------+-----------------+-------------------+
|        A (j)  |   PSID (K)      |        M  (i)     |
+---------------+----------+------+-------------------+
|<----a bits--->|<-----k bits---->|<------m bits----->|
                |<---c bits--->|<-----(k+m-c) bits--->|

Where:

* R = 2^k  
* M = 2^m
* j = (2^(16 - a) / M) / R to ((2^16 / M) / R) - 1 
* i = 0 to M - 1

_a_ is known as *PSID offset* while _k_ is known as *PSID length*. A is used to define excluded ports. Value by default is 6 bits (excludes first 1024 ports). A = 2^(16 - a).

Considering all these facts, it is possible to write down a function that calculates all possible port ranges for a given PSID:

```lua
local a = 6
local k = 7
local m = 2

local R = 2^k
local M = 2^m

local function port_ranges(K)
   assert(K >= 0 and K < R, "Incorrect PSID value")
   local ranges = {}
   local index_start, index_end = (2^(16-a) / M) / R, ((2^16 / M) / R) - 1
   for j = index_start,index_end do
      local start = R * M * j + M * K
      local last = start + M-1
      table.insert(ranges, range(start, last))
   end
   return ranges
end
```

The spec describes how to obtain a PSID value out of a port number:

```lua
local function port_to_psid(port)
   return math.floor(port/M) % R
end
```

What I think it is necessary to do to support PSID format is:

* Change the binding table format to store PSID numbers instead of a port range.
* Define constants R and M in a conf file. Possibly PSID length (a) too.
* Matching is done by converting an IPv4 port number to PSID and compare against the PSID value of a binding table entry.

**Comment by kbara** [comment]
I haven't carefully checked every detail, but it sounds plausible.
Just a thought: what about internally continuing to have our data structures internally use a start port and an end port, making this essentially a front-end change in how we specify them? Or do you see a reason to make it go deeper?

**Comment by dpino** [comment]
@kbara If I understood the spec correctly, I think the main advantage of using PSID format is that a single entry can cover a wide range of ports. For instance, following the example in "Extended IPv6 Addressing for Encoding Port Range" [1], which also describes the PSID format:

R=128 (k=7), M=4 (m=2)
PSID = 0, would cover 128 ranges ([1024-1027], [1536-1539], ..., [65024-65027])

We can, on the other hand, keep using our format, and in the preprocessing of the binding table obtain all the possible port ranges for a PSID and store them as individual entries in the binding table. I like this approach if it's temporal, it can also help us understand the implications of the PSID format. Once it's proved to work OK, I would like the binding table to natively support PSID as it's more efficient (requires 2 bytes less per entry, reduces the number of entries in the binding table, allows port exclusion, etc)

[1] https://tools.ietf.org/html/draft-bcx-behave-address-fmt-extension-01#page-5

**Comment by kbara** [comment]
Okdokie, cool.

**Comment by kbara** [comment]
'j' is being defined differently from http://tools.ietf.org/html/rfc7597#section-7.1 in this example. In RFC 7597, ```j:  Selects the specific port within a particular range specified by the concatenation of A and the PSID.```. Your table is from https://tools.ietf.org/html/draft-bcx-behave-address-fmt-extension-01 . This is ok, but we might want to avoid calling it 'j' to avoid confusion.

------

a + k + m must equal 16, which it doesn't in the code example above. 6 + 7 + 2 = 15.
a is not necessarily 6, although that's the default.

------

The 'port_ranges' function is wrong. A PSID uniquely identifies a port range, and isn't a set of port ranges (given that a and k MUST be the same for every MAP CE sharing an address, and by implication m must be as well, since they add up to 16). An example in the RFC:
```
 For example, the first 256 ports are represented as port prefix 0.0/8 and
 the last 256 ports as 255.0/8.  In hexadecimal, these would be
 0x0000/8 (PSID = 0) and 0xFF00/8 (PSID = 0xFF),
```
So, in that example, port_ranges(0) should just be the tuple [0, 255], rather than a huge list of [start, end] tuples, although that example also has different a/k/m values.
You -could- calculate a list of tuples a PSID could represent as a/k/m vary, but I don't see why we would, and that's also not what the code does.

**Comment by kbara** [comment]
I've looked at this harder, and made a working port range calculator. My earlier comment about port_ranges was incorrect. The following code matches the spec.

```
function calculate_ranges(psid, offset_bits_a, psid_len)
   local a, k, m = offset_bits_a, psid_len, 16 - offset_bits_a - psid_len
   print(string.format("a: %s, k: %s, m: %s", a, k, m))
   local R = 2^a -- sharing ratio
   local C = 2^m -- aka M, # contiguous ports

   -- If the sharing ratio is one, it's the full port range 
   if R == 1 then
      print(string.format("\t[%s-%s]", 0, C-1))
   end

   -- i must be > 0 if the port ranges are shared, by specification 
   for i=1, R - 1 do
      --local base = i * psid_len + psid
      --local base = R * C * i + C * k
      local base = i * 2^(k + m) + psid * 2^m
      print(string.format("\t[%s-%s]", base, base+C-1))
   end
end


print("Example 1, 63 ranges, offset = 6, psid = 0x34:")
calculate_ranges(0x34, 6, 8)

--[[
Example from 
http://tools.ietf.org/html/rfc7597#appendix-A
Available ports (63 ranges): 1232-1235, 2256-2259, ...... ,
                                63696-63699, 64720-64723
--
First A value is 1; it must not be 0, as per the spec
6 A bits = 0x1 = 0000 01
8 P bits = 0x34  0011 0100
2 J bits; 00 for first value in range, 11 for last
[A1 A2 A3 A4   A5 A6|P1 P2   P3 P4 P5 P6   P7 P8 | J1 J2]
  0  0  0  0    0 1   0  0    1  1  0  1    0  0    0  0 =  first port
  0  0  0  0    0 1   0  0    1  1  0  1    0  0    1  1 =  last port
  
  
  0  0  0  0    0 1   0  0    1  1  0  1    0  0    0  0 =  0x04d0 = 1232
  0  0  0  0    0 1   0  0    1  1  0  1    0  0    1  1 =  0x04d3 = 1235

Similar calculations apply for A=2, etc.
--]]

print("Example 2, full port range")
calculate_ranges(0, 0, 0
```

------------------------

The output:
```
Example 1, 63 ranges, offset = 6, psid = 0x34:
a: 6, k: 8, m: 2
	[1232-1235]
	[2256-2259]
	[3280-3283]
	[4304-4307]
	[5328-5331]
	[6352-6355]
	[7376-7379]
	[8400-8403]
	[9424-9427]
	[10448-10451]
	[11472-11475]
	[12496-12499]
	[13520-13523]
	[14544-14547]
	[15568-15571]
	[16592-16595]
	[17616-17619]
	[18640-18643]
	[19664-19667]
	[20688-20691]
	[21712-21715]
	[22736-22739]
	[23760-23763]
	[24784-24787]
	[25808-25811]
	[26832-26835]
	[27856-27859]
	[28880-28883]
	[29904-29907]
	[30928-30931]
	[31952-31955]
	[32976-32979]
	[34000-34003]
	[35024-35027]
	[36048-36051]
	[37072-37075]
	[38096-38099]
	[39120-39123]
	[40144-40147]
	[41168-41171]
	[42192-42195]
	[43216-43219]
	[44240-44243]
	[45264-45267]
	[46288-46291]
	[47312-47315]
	[48336-48339]
	[49360-49363]
	[50384-50387]
	[51408-51411]
	[52432-52435]
	[53456-53459]
	[54480-54483]
	[55504-55507]
	[56528-56531]
	[57552-57555]
	[58576-58579]
	[59600-59603]
	[60624-60627]
	[61648-61651]
	[62672-62675]
	[63696-63699]
	[64720-64723]
Example 2, full port range
a: 0, k: 0, m: 16
	[0-65535]
```

**Comment by kbara** [comment]
As for why a = 6 by default: that gives us the bit pattern 0x0400 for the first port of psid=0, aka 1024. This also explains why a=4 starts at 4096 - it's 0x1000.
(Both cases depend on excluding A = 0 if a > 0).

**Comment by mwiget** [comment]
Instead of dealing with ranges, why not calculating a bit mask that exposes just the psid, then apply that mask to the packets TCP/UDP/ICMP port number/id  and do the lookup with the result? 
The hash table's key contains the IPv4 address and the shifted psid (shifted to the left by m bits).

Adding the bit mask operations to the example code above:

```
local bit = require("bit")

function to_binary(value)
        -- Formats an incoming integer value into a 32 bit binary string
        convert = {["0"] = "0000",["1"] ="0001",["2"] ="0010",["3"] ="0011",
                ["4"] ="0100",["5"] ="0101",["6"] ="0110",["7"] ="0111",
                ["8"] ="1000",["9"] ="1001",["a"] ="1010",["b"] ="1011",
                ["c"] ="1100",["d"] ="1101",["e"] ="1110",["f"] ="1111"}

        -- Convert them to hex, because hex to binary is easy!
        sval = string.format("%08x",value)

        -- Look up binary equivalent of each hex digit
        local out = ""
        for c=5,8 do
                local vx = string.sub(sval,c,c)
                out = out .. convert[vx] .. ' '
        end
        return out
end

function calculate_psmask(psoffset, psid_len)
  local psmask = bit.band(bit.rshift(0xffff, psoffset), bit.lshift(0xffff,16 - psoffset - psid_len))
  return psmask
end

function calculate_ranges(psid, offset_bits_a, psid_len)
   local a, k, m = offset_bits_a, psid_len, 16 - offset_bits_a - psid_len
   print(string.format("a: %s, k: %s, m: %s", a, k, m))
   local R = 2^a -- sharing ratio
   local C = 2^m -- aka M, # contiguous ports

   local psmask = calculate_psmask(offset_bits_a, psid_len)
   print(string.format("psmask %04X %s", psmask, to_binary(psmask)))

   -- If the sharing ratio is one, it's the full port range
   if R == 1 then
      print(string.format("\t[%s-%s]", 0, C-1))
   end

   -- i must be > 0 if the port ranges are shared, by specification
   for i=1, R - 1 do
      --local base = i * psid_len + psid
      --local base = R * C * i + C * k
      local base = i * 2^(k + m) + psid * 2^m
      local psidkey = bit.band(psmask, base)
      print(string.format("\t[%s-%s] (%s)", base, base+C-1, psidkey))
   end
end


print("Example 1, 63 ranges, offset = 6, psid = 0x34:")
calculate_ranges(0x34, 6, 8)
```

shows that the calculated psidkey is 208 (which is 0x34 << 2):

```
$ luajit psmask.lua |more
Example 1, 63 ranges, offset = 6, psid = 0x34:
a: 6, k: 8, m: 2
psmask 03FC 0000 0011 1111 1100
        [1232-1235] (208)
        [2256-2259] (208)
        [3280-3283] (208)
        [4304-4307] (208)
        [5328-5331] (208)
...
        [63696-63699] (208)
        [64720-64723] (208)
```

and example with psid = 1:

```
Example 3, 63 ranges, offset = 6, psid = 1:
a: 6, k: 8, m: 2
psmask 03FC 0000 0011 1111 1100
	[1028-1031] (4)
	[2052-2055] (4)
...
```

While the offset and psid length can be different between binding entries, it has to be fix for bindings sharing the same IPv4 address. So the mask could be looked up via another hash table indexed by IPv4 address. This can be optimised if all binding entries share the same offset and length.

**Comment by dpino** [comment]
Development of this issue has been carried out in #161 and #185.

**Comment by dpino** [comment]
Support of this feature has landed in lwaftr_olive.
