### ISSUE TITLE
path_data.setter_for_grammar mangles path query containing /

### ISSUE THREAD

**Issue by benagricola** [Igalia/snabbswitch#1116]
I'm using `path_data.setter_for_schema_by_name()` to update a route entry - my path looks like this:

```
/routing/route[dest=0.0.0.0/0]
```

This throws `Syntax error in route[dest=0.0.0.0` - because the full path is split into `head` and `tail` on line 198 using `lib.dirname` and `lib.basename`.

These two have no concept of the `query` part of the path, so the above path is split into the following:

```
head = /routing/route[dest=0.0.0.0
tail = 0]
```

I'm happy to submit a PR with a fix for this - however I'm not certain what the fix should be.

My gut feeling is that the code to correctly parse the head and the tail already exists, as the top part of `parse_path()` in `lib.yang.path`. I have local code which splits the current `parse_path()` implementation:

```
parse_path()   - given a path, tokenise it and return a list of tokens
extract_path() - given a path, call parse_path(path) to get tokens, then extract_parts(element) over the returned non-empty elements.
```

The downside to this is that it changes the public API for most usage from `path.parse_path()` to `path.extract_path()`.

`path_data.setter_for_grammar()` must then use `parse_path` to split the parts, reconstructing `head` using `table.concat`, and extracting `tail` as the last item in the table.

Thoughts on whether this is an appropriate fix, or whether there's a way to fix this that I haven't thought of would be much appreciated 👍

**Comment by dpino** [comment]
I think the problem might be that the path doesn't refer to a leaf but to a list. How does your schema looks like? To me a path like that one would correspond to a schema like this one:

```
container routing {
   list route {
      key dest;
      leaf dest { type ipv4-address; }
   }
}
```
Thus, `/routing/route[dest=0.0.0.0/0]` returns a list. The `route` list should have a `value` leaf that stores the route value I think, so the path will be `/routing/route[dest=0.0.0.0/0]/value`, and in this case it would work since `lib.basedir` will return `value` and `lib.dirname` is `/routing/route[dest=0.0.0.0/0]`.

If what I'm saying is wrong and doesn't make sense, then yep you would need to use `parse_path` or `extract_parts` (I cannot find `extract_path` I think you meant `extract_parts`). I think `parse_path` will handle this case OK, but it's going to return you a data structure, not a path. About `extract_parts` I don't know if it will handle that case correctly.

**Comment by benagricola** [comment]
Yeah you're almost spot on with the schema, except `dest` is a string right now (passed directly into LPM), and route has additional attributes `gateway` (`ipv4-address`), `family` (`enum`) and `type` (`enum`)

```
container routing {
   list route {
      key dest;
      leaf dest { type string; }
      leaf gateway {type ipv4-address; }
      leaf family { type address-family; }
      leaf type { type route-type; }
   }
}
```

If I understand correctly, you're saying if I want to update multiple values from a single route, e.g.:

```
route {
    dest 0.0.0.0/0;
    gateway 1.2.3.4;
    family ipv4;
    type unicast;
}
```

I should be using `setter_for_schema_by_name` against `/routing/route[dest=0.0.0.0/0]/value` rather than against `/routing/route[dest=0.0.0.0/0]`?

**Comment by dpino** [comment]
I think I'm wrong. It should be possible to update something that is not a leaf. It's a case currently managed in the code: https://github.com/Igalia/snabb/blob/lwaftr/src/lib/yang/path_data.lua#L212

I think a possible fix (I haven't tried this but I think it could work) is replacing:

```lua
local head, tail = lib.dirname(path), lib.basename(path)
local tail_path = parse_path(tail)
local tail_name, query = tail_path[1].name, tail_path[1].query
```

For:

```lua
local head = parse_path(path)
local tail = table.remove(head, #head)  -- Now head contains "lib.dirname" and tail "lib.basename" correctly parsed.
local tail_name, query = tail[1].name, tail[1].query
```
Maybe it needs to manage edge-cases like a path with one single element.
