### ISSUE TITLE
Add ACL support

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#147]
@dpino are you willing to assign this to yourself?

**Comment by dpino** [comment]
PR #96 implements this feature partially. It enables to add ingress/egress filters for IPv4 and IPv6 packets in lwaftr.conf file. With regard to egress packets, the filter applies to ICMP packets too, which I'm not sure about it. The PR is pending to be review.

To implement ACL support, I'm going to create a new PR on top of PR #96.

**Comment by dpino** [comment]
Extended #96 to handle ACL compilation too.

**Comment by andywingo** [comment]
I think we should agree on a design before proceeding with further implementation.  To me the first step is to add ingress/egress filter support to the lwaftr program, via adding PcapFilter apps to the graph.  See https://github.com/Igalia/snabbswitch/blob/lwaftr_rambutan/src/program/snabb_lwaftr/setup.lua for where to add this support.  Then we implement a `snabb-lwaftr compile-acl foo.csv` command that spits out a pcap-filter string as text.  WDYT?

**Comment by dpino** [comment]
OK, so if I understand correctly, the idea is that instead of applying pcap filters in the lwaftr.lua code itself, implement filtering logic as independent apps that pipe with the reassemblers and lwaftr app to filter incoming and outgoing packets. I like this approach more.

The independent command to compile a ACL file to pcap-filter string sounds good to me. What's not clear is how to connect the pieces together. From my point of view, the lwaftr conf file contains a reference to an ACL file (if any it's going to be used). The parser either leaves this value as it is and later the PcapFilter compiles it (via the compile-acl command) to a pcap-filter string that it's later compiled to a Lua function with pflua. Or should the user compile the ACL file manually and paste the pcap-filter string into the lwaftr conf file?

**Comment by andywingo** [comment]
I was thinking the latter: that the use should compile the ACL file manually and paste the pcap-filter string into the lwaftr conf file.  Dunno.  It's terrible but the more I thought about it, it seemed like an ACL might be a misguided feature, and that really the network operator should be working directly with pcap-filter strings.  Having a tool just spit out a filter that you have to paste is a poor implementation of the requirement, though, I definitely agree :/

How about this.  We start with the external command and the cut-and-paste.  Then if we feel like it we add ingress_acl_file=file to the config, and make it populate the ingress_pcap_filter config option if ingress_pcap_filter isn't given a value.  WDYT?

**Comment by dpino** [comment]
OK, totally agree. Although less automatic, I think it's easier to think in terms of pcap-filter expressions to filter out packets than in terms of ACL files, easier to test plus it's an useful feature itself. And if finally implement the `ingress_pcap_filter` feature will be a small step after this.

**Comment by dpino** [comment]
Packet filtering support implemented in #207

**Comment by dpino** [comment]
ACL support is still pending but this issue has turned to be into adding packet-filtering support which was implemented in #207.
