### ISSUE TITLE
Automatically discover L2 address of router on IPv6 interface

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#148]

**Comment by andywingo** [comment]
The goal of this ticket is to support auto-configuration of next-hop L2 addresses for the lwaftr program (and I say program rather than app because this probably shouldn't be a thing we implement in the lwaftr app itself).

Having taken a brief look at the ARP RFC's, I still don't see how IPv4 routers determine the ethernet address of the next hop.  In our case that will be a router, and we certainly don't want to send out who-has packets for every IPv4 address we contact :)  My best guess is that the system would configure a default gateway, as an IPv4 address, and then we would use ARP to determine the ethernet address of the gateway.  Of course, ideally you would want to configure that gateway address using some northbound protocol, and with all that I think that ARP is probably too complicated for milestone 2.  Happily it appears to be something that we didn't promise to offer :)  In summary, let's not implement ARP for milestone 2, and instead statically configure the MAC of the router.

In the best of all possible worlds, it would be a separate app that stamps the L2 address of the IPv4-side traffic onto the packets, and that way we could avoid making the lwaftr app think about ethernet addresses at all.

On the IPv6 side we need to implement NDP.  Relative to the nd_light app that already exists (https://github.com/Igalia/snabbswitch/tree/lwaftr_rambutan/src/apps/ipv6) we need to add support for multiple IPv6 addresses, because the lwaftr has multiple IPv6 addresses.

With my Snabb hat on, we should certainly work on this upstream, incorporating our use case in the upstream nd_light app.  Thinking though of our timescales, I suggest we copy the nd_light app into the lwaftr directory and modify it there.  We'll try to keep our changes upstream-able and keep the interface the same while we learn about ND and make mistakes :)

**Comment by plajjan** [comment]
Indeed, you have a default route configured and ARP maps IP to MAC so you know what to put in the Ethernet header. ARP does not allow you to automatically discover the IP of your default gateway - that would be a job for DHCP or similar.

And I completely agree that this is outside of lwAFTR. Should preferably be a small separate app doing this :)

**Comment by kbara** [comment]
There are two different NDP-related things to consider:
a) NA/NS support (somewhat like ARP was for IPv4) - neighbour solicitation and announcement. I've extended nd_light and just need to test it. We need this for interoperability with openwrt.

b) Figuring out next hops. In practice, for the moment, I think we should just stay with our current "configure a next hop statically" approach. NDP's handling of router announcement/solicitation shouldn't be particularly hard to implement, but to meaningfully use the results (which are per-host), we'd risk hitting RAM an extra time per packet, which is problematic.

Indubitably, none of this belongs in the lwaftr app itself.

**Comment by wingo** [comment]
A question for @plajjan :)  What is the right thing to do on the ipv6 side?  We can statically configure a next-hop IPv6 address and get the right L2 address using ND, but as a person with ops experience I'm curious what you would want to see ideally -- is there a way for a router connected to a lwaftr to tell us "hey, all packets go to me and this is my L2 address" ?

**Comment by kbara** [comment]
I second the "what would you like to see ideally?" question.
@wingo The NDP spec contains router solicitation.

**Comment by plajjan** [comment]
@wingo yes, that would be router advertisement (RA) that the router sends out to notify clients on the network that it is default gateway for the network. (risk of stating the obvious) RA is sent periodically and RS can be sent by client to immediately request an RA and avoid waiting for the next periodic RA, thereby speeding it up.

I will admit that we haven't discussed this in detail internally but usually we try to avoid things such as RA and rely on static configuration instead and so I'm inclined to say that is what we want for this as well. There are multiple reasons for this:
 * I like things to be deterministic. Before we announce the anycast AFTR prefix (effectively notifying the rest of the network that we are ready to receive traffic) we should make sure that the AFTR is functional and knowing that we have a default route for IPv6 would be one of those checks. We would have to wait for the RA process to complete. Compare this to a static route where no wait is required. I guess you could argue that neighbor discovery needs to happen so you have the L2 destination for your default gateway but this is in itself a shorter and more deterministic process.
 * Explicit over implicit. Ties in to the above. Essentially that it's easier to troubleshoot or determine the behaviour of an application if you really on explicit configuration rather than implied state.
 * The decrease in amount of configuration needed by RA is minimal and since there are so many other things, like binding table, anycast prefix, IPv4 address & IPv4 routing that needs to be configured I don't see why we would try to minimise the config required by using RA over explicit config.

We are talking about an implementation here but even if RA/RS was readily available in Snabb I would opt for static configuration.

I will discuss with Ian so we are in sync on this.

**Comment by kbara** [comment]
Given discussion so far, I'm closing this; feel free to re-open. :-)
