### ISSUE TITLE
snabb-lwaftr --compile-table

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#151]

**Comment by kbara** [comment]
This presumably depends on https://github.com/Igalia/snabbswitch/issues/101

**Comment by andywingo** [comment]
There is a `snabb-lwaftr compile-binding-table` command: https://github.com/Igalia/snabbswitch/tree/lwaftr_rambutan/src/program/snabb_lwaftr/compile_binding_table

Loading a binding table from source will look first for a corresponding already-compiled binding table, and load that instead if the source's mtime is the same as the mtime embedded in the compiled table.  In this way you can use compile-binding-table to compile a table offline, and then send SIGHUP so that the lwaftr picks it up.

We should probably use a different mechanism for reload, though -- for example reloading automatically if the inode of the compiled binding table changes.  Will file another bug for potential binding table reload changes.
