### ISSUE TITLE
All 'snabb lwaftr' apps should be run by CI

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#412]
It can be a token test to just make sure they do something trivial without crashing, but it should be run on every pull request. Being able to do this even when they require hardware is one reason we moved to snabbbot from travis-ci.

**Comment by dpino** [comment]
Snabb-bot runs all selftest.sh scripts in the code base and all Lua files which contain a selftest function. It actually runs several lwAFTR apps, but only those ones which contain a selftest. For instance:

```
TEST      apps.lwaftr.dump
TEST      apps.lwaftr.lwdebug
TEST      apps.lwaftr.ndp
TEST      apps.lwaftr.fragmentv4_test
TEST      apps.lwaftr.fragmentv4_hardened
TEST      apps.lwaftr.V4V6
TEST      apps.lwaftr.conf
TEST      apps.lwaftr.fragmentv6_hardened
TEST      apps.lwaftr.rangemap
TEST      apps.lwaftr.channel
TEST      apps.lwaftr.podhashmap
```

https://gist.github.com/lwaftr-igalia/c64c25845f7a13c9bf7822c4feddf033

**Comment by kbara** [comment]
Yeah, that's not good enough - the test suite should be testing more, including the front ends, not just random unit testy bits.

**Comment by dpino** [comment]
Besides the Lua unit tests, Snabb-bot also runs all selftest.sh scripts in the code base. This is useful for writing more sophisticated tests, for instance tests that run a Snabb tool, setup a VM, run system tools, etc (an example of a test like this is the SnabbNFV test).

If we extended Snabb-bot to parse all the tools in program/lwaftr and simply run them, likely the output would be the help of those tools. It won't detect that a tool is broken, like happened the other day with "lwaftr query" because specifically in that case testing certain parts of its code involved having a running lwaftr instance (I believe this is true for other lwaftr tools). A test like this can be written as a selftest.sh script. If a tool doesn't involve such complexity it can be tested by adding a selftest() function that runs function "run()" with certain parameters. For instance that could be the case of "lwaftr check" which doesn't depend on other external tool.

Summarizing, if we want to test "lwaftr" apps front-ends we just need to write tests for them.

**Comment by kbara** [comment]
Obviously we don't want to just run the tools with no arguments after automatically detecting they exist and get the help...
I agree that invoking the front ends from selftest.sh scripts is a reasonable mechanism. The point is that we have to _actually do that_.

**Comment by dpino** [comment]
This task can be very time consuming for one person. I think it's better to split it in several subtasks, one selftest per UI tool, and let people work in one test at a time (instead of assigning all the tests to one single person). We need UI tests for the following tools:

- [x] lwaftr bench selftest.
- [x] lwaftr check selftest.
- [x] lwaftr config selftest.
- [x] lwaftr loadtest selftest.
- [x] lwaftr monitor selftest.
- [x] lwaftr query selftest.
- [x] lwaftr run selftest.

There's now a selftest for `lwaftr query` (#711), which can serve as reference. There are also UI tests for the `snabb config` subcommands (#658).

IMHO, the most important tests to have are `lwaftr run` and `lwaftr loadtest`.

**Comment by teknico** [comment]
I agree. Let's use this as a grouping issue and create new specific issues for each selftest when we get around to creating them.

**Comment by teknico** [comment]
Current situation:
- some initial tests in `src/program/lwaftr/selftest.sh`;
- config tests in `src/program/lwaftr/tests/config/`;
- query tests in `src/program/lwaftr/query/tests/`;

They use separate support code and different subcommand models.

In #736 I put some common code in `src/program/lwaftr/tests/common.sh`, and then used it when refactoring the config tests (#740) and the query tests (#741). Future tests will use it too.

**Comment by teknico** [comment]
Subcommand selftests have been implemented in Python using the infrastructure described in #749.

**Comment by teknico** [comment]
This is now complete.

**Comment by kbara** [comment]
Woo, well done! Thank you @teknico !
