### ISSUE TITLE
Identify yang fragment by schema path

### ISSUE THREAD

**Issue by tsyesika** [Igalia/snabbswitch#549]
There is an overarching goal of having a config program which can get, set, update and delete fragments of yang. The way to do this is to specify a path which will resolve to a specific node. The user then could also specify other attributes if it's for example a list to extract a specific item (for more detail on this see https://github.com/snabbco/snabb/issues/987)

This issue is to specifically to implement a mechanism to provide a path to the configuration program and for the program to resolve the specific node addressed and to display the fragment of yang data at said node. The ability to add, remove or set data will come in a later issue, however I will illude to how I invisage this working as it relates to the issue at hand.

The YANG RFC specifically calls out the use of xpath to find data in a data document. XPath is rather large with support for very complex operations. The RFC  include 27 different functions and 4 different types.

If we were to implement a basic XPath parser I we should implement a small subset. To lookup a specific node I think the XPath query would look something like this:

```
$ snabb config get -m snabb-softwire-v1 /snabb-softwire-v1/softwire-config/external-interface/ip
1.2.3.4
```

To lookup a leaf inside a list element you need to specify a path with an equivalency operator in it. This would be this:

```
$ snabb config get -m snabb-softwire-v1 /snabb-softwire-v1/binding-table/psid-map[addr=2.3.4.5]/psid-length
7
```

WDYT @wingo

**Comment by wingo** [comment]
I think we should also consider how we represent paths on the Lua level.  I suggest this:
- A path is a Lua array composed of path components
- A path component to access a struct field is a string, the name of the member
- A path component to access an array field is an integer (zero-based or one-based?)
- A path component to access a table item depends:
  - If it is a string-keyed table, then the path component is a string
  - Otherwise it is a table.  The keys of the Lua table are the keys to the corresponding leaf.  Keys with default values may be omitted.

**Comment by wingo** [comment]
This means that any xpath expression that can parse to the above path representation on the lua level works for us.  The xpath expressions that you mention would work fine.

**Comment by wingo** [comment]
Done via #590.
