### ISSUE TITLE
ARP support

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#564]
We need to deliver support for ARP in the lwAFTR.  Fortunately @kbara already implemented it :)  This issue is here so that by milestone v3.1, we have a description of the tests that we use to verify that ARP works as designed.

**Comment by kbara** [comment]
Our testing strategy, with ARP as a case study and details of how to test it on a live network, is outlined in https://github.com/Igalia/snabb/pull/669

**Comment by kbara** [comment]
The excerpt most relevant to ARP:

The overall project is developed as a series of smaller, more modular parts. For example, facilities like ARP and ping support are implemented as Snabb apps, independently of the main lwAFTR app; they are then all combined into an app network within Snabb. YANG support has a similar flavour; the majority of it is run in a separate process from the data plane. This makes it easier to test, easier to extend and change, and more reliable.

An example of our testing is how ARP support is tested. It has unit tests (in the function 'selftest()', following the convention to run unit tests automatically), which check how the request is formed, and the reply the library gives to that request. We also have two end-to-end tests for ARP; these specify an incoming packet, pass it through the whole app network, and make sure that the end result is byte for byte identical with what is expected. Both the implementation and the testing were done with careful attention paid to RFC 826 throughout, as well as to dumps of ARP packets from the live network the developer was on.

ARP has two main parts: resolving a remote address, and providing the address of the lwAFTR on request. The first one can be tested in a network by specifying only the remote IP of the next IPv4 hop (not the ethernet address), then sending packets through the lwAFTR and confirming on the remote host that they are arriving. The latter can be tested by issuing an ARP request to the lwAFTR from another machine; if the other machine runs Linux, arp -n should then show a new entry corresponding to the lwAFTR. The end to end tests simulate both of these cases, but with captured packets rather than a live network.
