### ISSUE TITLE
Cannot build large binding tables

### ISSUE THREAD

**Issue by dpino** [Igalia/snabbswitch#624]
I'm trying to launch `lwaftr run` with a large binding-table (2M). Here is a lwaftr config file with such binding-table:

https://people.igalia.com/dpino/lwaftr/lwaftr-migrated.conf

The configuration file is in v3.1.0 format. This configuration file is the result of a migration of the old lwaftr conf + binding-table files we used to use for benchmarking:

https://people.igalia.com/dpino/lwaftr/lwaftr.conf
https://people.igalia.com/dpino/lwaftr/binding_table.txt

When running `lwaftr run` with such configuration file, it apparently works but there's not .o file generated.

```
$ sudo ./snabb lwaftr run --conf lwaftr-migrated.conf --v4 82:00.0 --v6 82:00.1
Warning: No NUMA memory affinity.
Pass --cpu to bind to a CPU and its NUMA node.
lwaftr-migrated.conf: loading source configuration from lwaftr-migrated.conf
```

If I try to send packets to the lwaftr, nothing arrives. Debugging program/lwaftr/run I noticed that the process gets stuck at https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/run/run.lua#L138

**Comment by wingo** [comment]
It seems this is because the new yang parser uses too much memory.  It's not a complexity problem -- the parser still appears to be O(n) -- but a memory usage problem.  The configuration file itself is like 100Mbytes and it's thus quite conceivable that simply parsing the AST reaches LuaJIT's 1Gbyte limit (that seems to be what I'm seeing).  I don't yet know what the solution is :)
