### ISSUE TITLE
Write property based tests for yang

### ISSUE THREAD

**Issue by kbara** [Igalia/snabbswitch#631]
There are several properties that our yang implementation should have, including:
a) not crashing when given arbitrary sequences of gets and sets
b) having the same values after 2 or more of the same get or set (or interleavings thereof)

As a first step towards this, I am going to write some scaffolding code, similar to the property based testing we have in pflua, which generates a small subset of our yang commands, then hand it off to Asumu to add a wider range of commands and possibly more properties.

**Comment by wingo** [comment]
Sounds good.

WDYT about framing this in terms of "snabb config" commands rather than "yang" commands?  Yang is the schema, not the operations on data.  Do you plan to test against a running snabb instance, or do this in an in-process way?  Probably it would be most useful to use "snabb config" on a live lwaftr instance, possibly via the listen interface.  Ideally we could have properties for what happens on the data plane as well, if we have an expectation for how a change would affect the data plane (e.g. adding an entry should have no effect on traffic).

**Comment by kbara** [comment]
Was still thinking about that. Testing with snabb config is higher overhead, but seems like a good initial way to go to me.

**Comment by wingo** [comment]
Yeah the thing is that the library interface is still a bit gnarly on the inside; snabb config commands don't map directly to library concepts.  There's a lot of logic in "snabb config".  Therefore to me it makes sense to focus testing efforts on the documented public interface rather than on internals.

**Comment by kbara** [comment]
Ok, perfect, I'm glad we talked that through.

**Comment by takikawa** [comment]
This issue was addressed via #703.
