### ISSUE TITLE
Arrange to create release tarballs for each git commit via hydra

### ISSUE THREAD

**Issue by wingo** [Igalia/snabbswitch#642]
In Guile we have a hydra integration that makes release tarballs for every git revision.  We should have this in Snabb hydra as well so that our release process is a simple reproducible tag and the bot handles the rest.  The complication for doing this in Hydra is the because we ship a binary, we need to make the build on a FHS system, not with Hydra's ld.so paths (https://github.com/Igalia/snabb/issues/49).

**Comment by dpino** [comment]
Rereading #49 what sounds more reasonable to me now is what Luke proposed, to build the binary inside a Docker container.

**Comment by teknico** [comment]
@wingo, would you please share the script you currently use to create the tarball, for comparison? Thanks.

Also, where shall we upload the release tarballs? http://people.igalia.com/awingo/ or somewhere else?

**Comment by wingo** [comment]
I do `make dist PACKAGE=snabb-lwaftr DIST_BINARY=snabb-lwaftr` in the root of the snabb checkout.

We should upload tarballs somewhere else, but I think that's a question we can answer later, after hydra is generating the tarballs.

**Comment by lukego** [comment]
> what Luke proposed, to build the binary inside a Docker container.

Just $0.02: Nix has completely replaced Docker in my world view nowadays.

**Comment by dpino** [comment]
@lukego Would it be possible to make the whole task only using NixOS? From my point of view, building the FHS-compatible binary inside a container is the only way to go, but perhaps I'm missing something. There's `patchelf`, but I don't know if it's completely reliable. Somehow using Docker seems safer to me for this use case.

**Comment by lukego** [comment]
My impression is that patchelf solves the problem. You can install Nix on any Linux platform and it will successfully build itself and other software like Snabb. If patchelf were not reliable then it seems like this would not work. (I'm running Nix on my laptop in an Ubuntu chroot on ChromeOS and running all kinds of software that was built by the Nix upstream Hydra and installed on my laptop with nix-env.)

Docker is a legit solution too. I just don't want to endorse it personally because I only view it as a distribution tool these days. For build and test I see it having more moving parts and less reproducibility than Nix.

**Comment by kbara** [comment]
I entirely agree with @lukego , fwiw.

**Comment by dpino** [comment]
@lukego thanks for sharing your thoughts. If `patchelf` can do the job I think we can skip all the Docker overhead. What do you think @teknico ?

**Comment by teknico** [comment]
It does simplify things considerably, if it works well enough. I'll give it a try.

**Comment by teknico** [comment]
A release tarball, with a correctly patched executable, is being generated (on-demand for now) by a [Hydra jobset](https://hydra.snabb.co/jobset/igalia/snabb-lwaftr-release). We have to decide a few details about how this is working, see comments in [the code](https://github.com/Igalia/snabb/blob/automate-release/tarball.nix) for details.

**Comment by teknico** [comment]
Policy agreed upon with @dpino:

- we will always create annotated release tags (see `git help tag`), not lightweight ones, so that we don't need to change the Hydra code (which currently does not track lightweight tags);
- the Hydra jobset will generate a tarball for each and every commit to the `lwaftr` branch, and make them available directly;
- the Hydra jobset will check for new commits every five minutes, and retain the last 50 generated tarballs.

**Comment by teknico** [comment]
Implemented by #733.
