### ISSUE TITLE
Move PSIDMap onto softwires

### ISSUE THREAD

**Issue by tsyesika** [Igalia/snabbswitch#792]
We would like to fold `/softwire-config/binding-table/psid-map` into a container on `/softwire-config/binding-table/softwire`. This would prevent bugs from creeping in such as #727 and also make the lwaftr easier to configure.

**Comment by dpino** [comment]
I believe this change will target snabb-softwire-v2. 

On a related note, there was an issue about removing end-addr (#641). The issue is closed as this feature was implemented in #696. However the fix was reverted as it had an horrible effect on files which still use the end-addr feature. Anyway, the #641 issue should have been reopened since the fix was reverted. This issue should tackle now the remove of end-addr feature too I think.

**Comment by tsyesika** [comment]
I believe this has been done so I'm closing this.
